name: Fetch and Compute Hourly

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  fetch-and-compute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Fetch & Compute
        run: |
          python fetch.py
          python compute.py

      - name: Commit CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add realtime_features.csv computed_features.csv
          git commit -m "Update features [skip ci]" || echo "No changes"
          git push
