name: Train and Predict Daily

on:
  schedule:
    - cron: '0 2 * * *' 
  workflow_dispatch:

jobs:
  train-and-predict:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Training & Prediction
        run: |
          python train.py
          python predict.py
          
      - name: Upload predictions
        uses: actions/upload-artifact@v4
        with:
          name: aqi-predictions
          path: predicted_aqi_predictions.csv
