name: Train and Predict Daily

on:
  schedule:
    - cron: '0 14 * * *' 
  workflow_dispatch:

jobs:
  train-and-predict:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training & Prediction
        run: |
          python train.py
          python predict.py

      - name: Upload prediction CSVs
        uses: actions/upload-artifact@v3
        with:
          name: predicted-data
          path: |
            predicted_next_3_days.csv
            realtime_features.csv
            computed_features.csv
